// hmr-react/src/Counter.js
import React, { Component } from 'react'
import { hot } from 'react-hot-loader'

import './Counter.scss'

export class Counter extends Component {
  state = { count: 0 }

  // Arrow fx for auto binding
  decrement = () =>
    this.setState(({ count }) => ({
      count: count - 1,
    }))

  // Arrow fx for auto binding
  increment = () =>
    this.setState(({ count }) => ({
      count: count + 1,
    }))

  render() {
    return (
      <div className="counter">
        <button onClick={this.decrement}>⬅️</button>
        {this.state.count}
        <button onClick={this.increment}>➡️</button>
      </div>
    )
  }
}

export default hot(module)(Counter)

// hmr-vue/src/components/Counter.vue
<template>
  <div class="counter">
    <button v-on:click="decrement">⬅️</button>
    {{count}}
    <button v-on:click="increment">➡️</button>
  </div>
</template>

<script>
export default {
  name: 'Counter',
  data: () => ({ count: 0 }),

  methods: {
    decrement() {
      this.count--
    },
    increment() {
      this.count++
    },
  },
}
</script>

<style scoped>
button {
  font-size: 100%;
}

button:first-of-type {
  margin-right: 0.5em;
}

button:last-of-type {
  margin-left: 0.5em;
}
</style>
